name: Tests Enterprise

on:
  push:
    branches:
      - main
      - v2.**
      - v3.**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  predis-enterprise:
    name: PHP 8.0 (Redis EE)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone Redis EE docker repository
        run: |
          git clone https://github.com/vladvildanov/redis-ee-docker.git redis-ee

      - name: Install Docker-compose
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose

      - name: Build cluster
        run: |
          export IMAGE=redislabs/redis:latest
          export RE_USERNAME=test@test.com
          export RE_PASS=12345
          export RE_CLUSTER_NAME=test
          export OSS_CLUSTER=false
          export DB_PORT=6379

          cd redis-ee/
          ./build.sh

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: relay, apcu
          ini-values: apc.enable_cli=1

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest

      - name: Run tests
        run: vendor/bin/phpunit
