name: Test Report
on:
  push:
    branches:
      - main
      - v2.**
  pull_request:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: PHPUnit Tests
          path: 'report.xml'
          reporter: java-junit
